//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NailsEntities1 : DbContext
    {
        public NailsEntities1()
            : base("name=NailsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_event> tb_event { get; set; }
        public virtual DbSet<tb_service1> tb_service1 { get; set; }
        public virtual DbSet<tb_service2> tb_service2 { get; set; }
        public virtual DbSet<tb_servicedetails> tb_servicedetails { get; set; }
        public virtual DbSet<tbl_about> tbl_about { get; set; }
        public virtual DbSet<tbl_aboutus> tbl_aboutus { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_banner> tbl_banner { get; set; }
        public virtual DbSet<tbl_contact> tbl_contact { get; set; }
        public virtual DbSet<tbl_gallery> tbl_gallery { get; set; }
        public virtual DbSet<tbl_Ournails> tbl_Ournails { get; set; }
        public virtual DbSet<tbl_service> tbl_service { get; set; }
        public virtual DbSet<tbl_home> tbl_home { get; set; }
    }
}
