//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_event
    {
        public int ma_e { get; set; }
        public string ten_e { get; set; }
        public string gia_full { get; set; }
        public string gia_fill { get; set; }
        public string hienthi { get; set; }
        public string noidung_e { get; set; }
        public string tieude_e { get; set; }
        public string path { get; set; }
    }
}
