//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_service2
    {
        public int ma_dvc2 { get; set; }
        public string ten_dvc2 { get; set; }
        public string gia_full { get; set; }
        public string gia_fill { get; set; }
        public string hienthi { get; set; }
        public Nullable<int> ma_dv { get; set; }
        public Nullable<int> ma_dvc1 { get; set; }
    }
}
