//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servicedetails
    {
        public int ma_dvct { get; set; }
        public Nullable<int> ma_dv { get; set; }
        public Nullable<int> gia_dv { get; set; }
        public Nullable<int> gia_dv_full { get; set; }
        public Nullable<int> gia_dv_fill { get; set; }
        public string hienthi { get; set; }
        public string ten_dvct { get; set; }
        public string ghichu { get; set; }
        public string path { get; set; }
    }
}
