//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_service
    {
        public int ma_dv { get; set; }
        public string nameid { get; set; }
        public string path { get; set; }
        public string noidung { get; set; }
        public string hienthi { get; set; }
        public Nullable<int> thutu { get; set; }
        public string class_bg { get; set; }
        public string path1 { get; set; }
        public string noidung1 { get; set; }
        public string nameid1 { get; set; }
    }
}
