//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_aboutus
    {
        public int id_aboutus { get; set; }
        public string noidungc1 { get; set; }
        public string path { get; set; }
        public string hienthi { get; set; }
        public string noidungc2 { get; set; }
    }
}
